### ISSUE TITLE
Integrating with Phoenix

### ISSUE THREAD

**Issue by nathany** [easco/absinthe_apollo_sockets#6]
Hi Scott. Thanks for the library. 

Do you have an example of how to integrate this with Phoenix?

I'm looking at: https://github.com/easco/absinthe_apollo_sockets/blob/master/examples/apollo_cowboy/lib/apollo_cowboy.ex#L11-L17

Not sure how to incorporate this while still keeping the Phoenix Cowboy2Handler.

Ideally, I'd like to keep `absinthe_phoenix` around for GraphiQL, perhaps putting Apollo Sockets at a different path.

**Comment by easco** [comment]
Howdy.

It has been a really long time since I looked at this.  I seem to remember doing work on Cowboy 2 and Phoenix 1.5... let me see if I have anything around that I've not checked in.

I never really put the stuff in this project into production.  If it works for you then great, if not... well, I wouldn't be surprised :-)

**Comment by easco** [comment]
OK... What I was remembering was doing the work to move from Cowboy 1 to Cowboy 2 _so that_ I could create a Phoenix sample.  And then never did it 👎 

Let me see what happens if I spend some time on it.

**Comment by easco** [comment]
OK I added a Phoenix sample.   The majority of the changes were in the config and in the set of children started by Phoenix's main supervisor.  Sample usage of the apollo client from Javascript is in the app.js file.  Start Phoenix, point your browser at localhost:4000 and you should see messages confirming that the subscription is receiving mutation messages.

**Comment by easco** [comment]
Incidentally instructions to keep the Phoenix handler is in the docs (https://hexdocs.pm/phoenix/Phoenix.Endpoint.Cowboy2Adapter.html#content) under the heading of "Custom dispatch options".   Basically you replace the entire cowboy dispatcher, make sure it captures your custom handler endpoint first, then let everything else go to the Phoenix adapter.

**Comment by nathany** [comment]
@easco Thanks so much for this sample, that helps a lot. Also for the link to the docs that I missed.

I haven't got it working quite yet. The code I am looking at had `use Absinthe.Phoenix.Endpoint` ([source](https://github.com/absinthe-graphql/absinthe_phoenix/blob/master/lib/absinthe/phoenix/endpoint.ex)), whereas PhoenixSample creates it's own Absinthe.PubSub. Would you recommend against keeping the `absinthe_phoenix` library around?

I also need to get this working with HTTPS and troubleshoot some errors. You got me on the right path though. Thanks!

NOTE: FYI, I ran into a number of odd errors trying to run PhoenixSample, mostly with Node.js (running 15.11.0)

**Comment by easco** [comment]
Off the top of my head, I can’t think of why it would matter if you kept the Absinthe Phoenix handler around, unless absinthe gets confused  because both absinthe and the Apollo socket code are trying to use the same pubsub and their wires get crossed listening for notifications.  If that is the case, however, you should be able to create yet another Phoenix pub sub (like the cowboy example does) and use this new, custom pup sub for Apollo and let absinthe continue to use the pubsub that the endpoint uses.

**Comment by nathany** [comment]
Thanks @easco.
